on:
  workflow_call:
  
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - 'master'
      - 'release'
      - 'main'

jobs:
  pr-title-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node JS
        uses: actions/setup-node@v2

      - name: Install commitlint
        run: npm install commitlint @commitlint/config-conventional

      - name: Install the shared config
        run: npm install git://github.com/taptapsend/commitlint-config.git  

      - name: Lint the PR title
        run: |
          (cat <<EOF
          ${{ github.event.pull_request.title }}
          EOF
          ) | npx commitlint --config ./node_modules/commitlint-config/.commitlint.config.js
