on:
  workflow_call:
  
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - 'master'
      - 'release'
      - 'main'

jobs:
  title-and-description:
    runs-on: ubuntu-latest

    steps:
      - name: Add Jira ticket to PR title / add links to PR description
        continue-on-error: true
        uses: onrunning/jira-pr-action@01969734035664e672cf51ae8c42f91331ec2d3e # v2
        with:
          jira-account: taptapsend
          ticket-regex: |
            \(?\[?[a-zA-Z][a-zA-Z0-9]{1,9}-\d+\]?\)?
          clean-title-regex: |
            [A-Z][a-z]{1,9} \d+\/
  pr-title-lint:
    runs-on: ubuntu-latest
    needs: title-and-description
    steps:
      - name: Install Node JS
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
      - name: Install commitlint
        run: npm install commitlint @commitlint/config-conventional
      - name: Install the shared config
        run: npm install git://github.com/taptapsend/commitlint-config.git  
      - name: Get current PR details
        id: findPr
        uses: jwalton/gh-find-current-pr@f3d61b485d2801773f7a07b2aaa3306bd8f8e653 # v1
      - name: Lint the PR title
        run: |
          (cat <<EOF
          ${STEPS_FINDPR_OUTPUTS_TITLE}
          EOF
          ) | npx commitlint --config ./node_modules/commitlint-config/.commitlint.config.js
        env:
          STEPS_FINDPR_OUTPUTS_TITLE: ${{ steps.findPr.outputs.title }}

